//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_changing_minimal_price
    {
        public int id { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual products products { get; set; }
    }
}
