//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public int id { get; set; }
        public Nullable<int> id_typeMaterial { get; set; }
        public Nullable<int> id_measurement { get; set; }
        public Nullable<int> id_provider { get; set; }
        public string name { get; set; }
        public Nullable<int> count { get; set; }
        public string description { get; set; }
        public string img { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual materialType materialType { get; set; }
        public virtual measurement measurement { get; set; }
        public virtual provider provider { get; set; }
    }
}
