//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partners()
        {
            this.history_sale_product = new HashSet<history_sale_product>();
            this.partnerProducts = new HashSet<partnerProducts>();
            this.salesPoints = new HashSet<salesPoints>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_partnerType { get; set; }
        public Nullable<int> id_contact { get; set; }
        public Nullable<int> id_adress { get; set; }
        public string name { get; set; }
        public string inn { get; set; }
        public Nullable<int> rating { get; set; }
    
        public virtual adress adress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<history_sale_product> history_sale_product { get; set; }
        public virtual partnerContact partnerContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partnerProducts> partnerProducts { get; set; }
        public virtual partnerType partnerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salesPoints> salesPoints { get; set; }
    }
}
