//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerProducts
    {
        public int id { get; set; }
        public Nullable<int> id_products { get; set; }
        public Nullable<int> id_partner { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual partners partners { get; set; }
        public virtual products products { get; set; }
    }
}
